### ISSUE TITLE
Allow recursive translations folder

### ISSUE THREAD

**Issue by Paillat-dev** [nicebots-xyz/botkit#67]
Allow to use a folder called translations and use subfolder names as keys.
e.g.
```
/src/extensions/my_extension/translations/commands/my_command.yaml
/src/extensions/my_extension/translations/commands/my_other_command.yaml
```
is equivalent to
```yaml
# /src/extensions/my_extension/translations.yaml

commands:
  my_command:
    ...
  my_other_command:
    ...
```
